name: Context
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.actor }}"
      - run: echo "${{ github.id }}"
      - run: echo "${{ github.head_ref }}"
      - run: echo "${{ github.workspace }}"
      - run: echo "${{ github.repository }}"
      - run: echo "${{ github.repository_owner }}"
      - run: echo "${{ github.event }}"
